Fix problems with Jupyter and Fish.

diff --git a/git_template/hooks/pre-push b/git_template/hooks/pre-push
--- a/git_template/hooks/pre-push
+++ b/git_template/hooks/pre-push
@@ -1,7 +1,3 @@
 #!/bin/sh
-
-local_hook="$HOME"/.git_template.local/hooks/pre-push
-
-if [ -f "$local_hook" ]; then
-  . "$local_hook"
-fi
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
+git lfs pre-push "$@"
